### ISSUE TITLE
Error running create_tf_records.sh

### ISSUE THREAD

**Issue by BenJourdan** [eldar/differentiable-point-clouds#2]
I've managed to download and extract the chair rendered images. I couldn't get your  `download_train_data.sh` to work for some reason so I did it manually by  using `wget {url}`. However when I tried to run `create_tf_records.sh` I got this error:
![tempsnip](https://user-images.githubusercontent.com/13700535/61595163-99f2c800-abeb-11e9-97b4-c9355e62e1b6.png)

What's supposed to be in `03001627.file` ? Do I need to use curl as you do in your download script?

I'm running this on Ubuntu.

**Comment by eldar** [comment]
Hey, sorry for a late reply. Please follow the instructions carefully: https://github.com/eldar/differentiable-point-clouds#prepare-training-data. You have to pass the ID of Shapenet category to the `create_tf_records.sh` script, in the case of chairs it is `03001627`.

**Comment by BenJourdan** [comment]
No worries. I think it was something unrelated. I had passed the `ID` to the script but it still wouldn't work. After restarting ubuntu (Windows subsystem for linux ubuntu) and cloning the repo again everything worked fine.
